name: Deploy to VPS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, xml, curl, pdo_mysql
          tools: composer:v2

      - name: Install backend dependencies
        run: composer install --prefer-dist --no-dev --optimize-autoloader

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'

      - name: Install frontend dependencies
        run: npm ci

      - name: Build frontend
        run: npm run build

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/keen.sardarit.cloud
            
            # Maintenance mode on
            php artisan down || true
            
            git pull origin main
            
            # Install dependencies on server
            composer install --optimize-autoloader --no-dev
            npm ci
            npm run build
            
            # Permissions
            sudo chown -R apache:apache .
            sudo find . -type d -exec chmod 755 {} \;
            sudo find . -type f -exec chmod 644 {} \;
            sudo chmod -R 775 storage bootstrap/cache
            
            # Optimization
            php artisan optimize:clear
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            
            # Maintenance mode off
            php artisan up
            
            sudo systemctl restart nginx



